import logging

from app.exceptions.api_exceptions import LlmGenerationError
from app.schemas.llm import LlmDecision

logger = logging.getLogger(__name__)

OLLAMA_AMBIGUOUS = "AMBIGUOUS"
OLLAMA_UNSUPPORTED = "UNSUPPORTED"
CLARIFICATION_MESSAGE = (
    "The question is related to the sales data, but it is ambiguous. Please "
    "clarify the metric and columns to evaluate, such as revenue, quantity "
    "sold, ticket count, average ticket value, product, waiter, date, weekday, "
    "or hour."
)
UNSUPPORTED_MESSAGE = "This question cannot be answered from the sales table."


def _strip_optional_sql_code_fence(output: str) -> str:
    lines = output.splitlines()
    if len(lines) < 3:
        return output

    opening = lines[0].strip().lower()
    closing = lines[-1].strip()
    if opening not in {"```", "```sql"} or closing != "```":
        return output

    return "\n".join(lines[1:-1]).strip()


def _is_valid_sql_output(output: str) -> bool:
    lowered = output.lower()
    return (
        lowered.startswith("select")
        and "```" not in output
        and not lowered.startswith("{")
        and not lowered.startswith("[")
    )


def parse_ollama_raw_output(raw_output: str) -> LlmDecision:
    output = raw_output.strip()
    normalized_label = output.removesuffix(".")

    if normalized_label == OLLAMA_AMBIGUOUS:
        return LlmDecision(
            type="ambiguous",
            sql=None,
            message=CLARIFICATION_MESSAGE,
            confidence=None,
        )

    if normalized_label == OLLAMA_UNSUPPORTED:
        return LlmDecision(
            type="unsupported",
            sql=None,
            message=UNSUPPORTED_MESSAGE,
            confidence=None,
        )

    if not output:
        raise LlmGenerationError("Ollama returned an empty response.")

    output = _strip_optional_sql_code_fence(output)
    if not _is_valid_sql_output(output):
        logger.warning(
            "Ollama returned unexpected SQL decision output raw_output=%r",
            output,
        )
        raise LlmGenerationError(
            "Ollama returned a response that does not match the expected SQL decision format."
        )

    return LlmDecision(
        type="query",
        sql=output,
        message="SQL generated by Ollama.",
        confidence=None,
    )
